/**
 * Creating an sidebar entry.
 * Learn more at @link https://docusaurus.io/docs/using-docs#sidebar
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 for Humanoid Robotics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo & Unity for Humanoid Simulation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-gazebo-unity',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac for Humanoid AI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-nvidia-isaac',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action for Humanoid Robotics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        },
      ],
    },
  ],
};

module.exports = sidebars;